spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: glebushnik
    password: glebushnik
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
  enabled: true
  baseline-description: "init"
  baseline-version: 0
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}

server:
  port: 8060

